### PR TITLE
Add new stackoverflow plugin

### PR DESCRIPTION
**Pull request by BrainMaestro**
I just got this up to a decent point. Can you take a look? Any pointers would be welcome

### CODE REVIEW

**Comment by KELiON** [comment]
@BrainMaestro hey! It looks awesome, I'm definitely going to use it! I have just two comments and only one is critical:

1) Looks like somewhere you've imported global styles and it breaks some cerebro styles:

example

2) I'd try to reuse colors, based on css variables from themes ([light](https://github.com/KELiON/cerebro/blob/master/app/main/css/themes/light.css) and [dark](https://github.com/KELiON/cerebro/blob/master/app/main/css/themes/dark.css)). It will guarantee that you plugin looks good with any selected theme. I.e. now on dark theme it looks like this: 

screen shot 2017-02-10 at 22 21 38

Anyway, it looks really good and if you want you can leave it like this.

**Comment by BrainMaestro** [comment]
Okay thanks! I'll look into both of them. Will this be merged? Or until I've fixed the issues?

**Comment by KELiON** [comment]
@BrainMaestro I've just found one more issue – I've tried to install the plugin, but published version doesn't work, it fails on plugin loading: 

image

**Comment by BrainMaestro** [comment]
Any idea why? I can't see the error you got, but it's not installing

**Comment by KELiON** [comment]
@BrainMaestro I've just checked and found that issue with js minifier babili. If you update its version to the latest it works. I've created [PR](https://github.com/BrainMaestro/cerebro-stackoverflow/pull/1) with update in your repo. Just do `npm install` and publish new version to npm to fix it.

> I can't see the error you got, but it's not installing
I think it is not installing because it is unpacked incorrectly, I [fixed](https://github.com/KELiON/cerebro/pull/108) this bug. You can try one of these test builds:

https://www.dropbox.com/sh/k9lhrdygc2jucl6/AABvnqJFqmlWXFmaHYJHxDtka?dl=0
https://www.dropbox.com/s/g0sbz96q1nck13s/Cerebro%20Setup%200.2.5.exe?dl=0
https://www.dropbox.com/s/lqfxs7c4rnw3hur/cerebro_0.2.5_amd64.deb?dl=0
https://www.dropbox.com/s/3x27uiuc6u3gnpu/cerebro-0.2.5-x86_64.AppImage?dl=0

**Comment by KELiON** [comment]
@BrainMaestro let me know when you update babili and fix global styles so I'll merge this PR

**Comment by BrainMaestro** [comment]
I updated the babili to `0.0.11`. I updated my cerebro too, but my plugin and some others still won't install. It just stops at the unarchiving stage. 
screen shot 2017-02-13 at 9 08 45 am

**Comment by KELiON** [comment]
@BrainMaestro can you double check that you're using the latest version of Cerebro? Installation works for me.

You can try to run `require('electron').remote.app.getVersion()` in console, it should be version 0.2.6.

**Comment by BrainMaestro** [comment]
Yeah it works now. I'm going to update the global styles. Thanks a lot

**Comment by BrainMaestro** [comment]
It should stop overriding global styles now

**Comment by KELiON** [comment]
@BrainMaestro awesome!

**Pull request merged**
