### PR TITLE
Fix plugin installation

### PR DESCRIPTION
**Pull request by KELiON**
On windows and Linux `os.tmpdir()` could be not empty, so we should create subdirectory for extracted package

### CODE REVIEW

**Comment by maximbaz** [comment]
Should I go ahead and test it? 🙂

**Comment by AlexAlabyev** [comment]
@KELiON I will test it on Windows, as well, when the new build is ready. 
Also, while we are talking about the plugins, how hard do you think would it be to implement this [https://github.com/KELiON/cerebro/issues/200](https://github.com/KELiON/cerebro/issues/200) ?

**Comment by maximbaz** [comment]
Plugins are being correctly installed and uninstalled now, good job 😉 

I have found, that some plugins have issues, and yet they are reported as installed (no errors, the button says "Uninstall"). The only information about this is in the console. 

I'm not sure if this is what you wanted to do in the step "Show errors during installation in UI", but if not, consider also making a visual indication about this, so that people know to file bugs for these plugins.

For example:

```
Load plugin: cerebro-stackoverflow
main.bundle.js:30556 Path: /home/maximbaz/.config/Cerebro/plugins/node_modules/cerebro-stackoverflow...
main.bundle.js:30519 Error requiring /home/maximbaz/.config/Cerebro/plugins/node_modules/cerebro-stackoverflow
main.bundle.js:30520 SyntaxError: Unexpected token }(…)
main.bundle.js:30559 Plugin is not valid, skipped
```

```
Load plugin: cerebro-hash
main.bundle.js:30556 Path: /home/maximbaz/.config/Cerebro/plugins/node_modules/cerebro-hash...
main.bundle.js:30559 Plugin is not valid, skipped
```

/cc @BrainMaestro, @codingmatty - you may want to try to reinstall your plugins on stable Cerebro and see if you also get these errors.

**Comment by KELiON** [comment]
> I'm not sure if this is what you wanted to do in the step "Show errors during installation in UI"

No, I was thinking just to show some message if there is a network/unarchive error (i.e. no free space on drive or something else). In your case looks like plugin is installed, but requiring it causes an error

@AlexAlabyev I've updated builds in dropbox, you can use the same links:

https://www.dropbox.com/s/hylenaysj374lqg/Cerebro%20Setup%200.2.6.exe?dl=0

Regarding #200 we can implement sorting for the next release, but grouping is a bit tricky because currently there is no way to group results

**Comment by maximbaz** [comment]
I think as long as the list just hides incompatible plugins and puts installed on top, that would be already a great improvement.

**Comment by BrainMaestro** [comment]
@maximbaz thanks for the shout-out. I'll check with the new build.

Is that a viable way to check for plugin incompatibility? What of plugins like cerebro-kill that is Mac only but can't be inferred from the name? I think we could use the keywords specified by the author in the package.json. So plugins with the 'windows' keyword don't show up on Linux and vice versa. Or it could be a separate key in the package.json file like 'platforms' or something. Just have to ensure the authors follow the convention. Thoughts?

**Comment by maximbaz** [comment]
It's a matter of convenience and balance. I thought of using the name because that allows you to immediately tell the incompatibility, without downloading any extra files like package.json. But at the same time I acknowledge, not all plugins unfortunately follow this naming convention. 

I wonder how hard is it to rename the plugin, once it was released? Cerebro won't probably be able to tell, that two plugins with different names are actually one plugin that was renamed?

**Comment by BrainMaestro** [comment]
Yeah, and there's also the issue of a plugin that supports multiple platforms. A plugin could conceivably be built that supports both macOS and Linux. How would that be specified with the naming convention? But yeah I agree with your reservation of downloading any files at all.

**Comment by AlexAlabyev** [comment]
@KELiON just tested the build on Windows, it all works fine now. Plugins are getting installed without app restart, and the bug with the permanent "uninstall" state is fixed as well.

**Comment by KELiON** [comment]
@BrainMaestro there is default "os" [flag](https://docs.npmjs.com/files/package.json#os) in package.json, that I wanted to use to check platform compatibility, but as @maximbaz already mentioned it requires one more request to get `package.json`. Available flags you can check in [this](https://registry.npmjs.com/-/v1/search?from=0&size=500&text=keywords:cerebro-plugin) request. Adding keyword can solve the problem, but it is much harder to support.

**Comment by BrainMaestro** [comment]
Okay the `os` flag would have been ideal. But it seems like there's no way to search by by `os`, while we can search by keywords. Something we could do is adopt a convention of listing the platform a plugin supports with `cerebro-${platform}` in the keywords section of a plugin's `package.json`. So for linux: `cerebro-linux`, macOS; `cerebro-darwin`, windows: `cerebro-windows`. That way, in the initial request to fetch available plugins, all we have to do is add the platform keyword to the search. So for windows the request will be `https://registry.npmjs.com/-/v1/search?from=0&size=500&text=keywords:cerebro-windows`. Which will only fetch windows compatible plugins. 

The only downside to this is requiring plugin authors to include the correct platform  keywords in their plugin or it won't show up as installable. This can be added to the plugin documentation though.

There could also be a catch-all with something like `cerebro-*`. Other suggestions for the platform keyword prefix are `cerebro-plugin-${platform}`, `cerebro-platform-${platform}` .

Thoughts?

**Comment by KELiON** [comment]
@BrainMaestro sound good, but I see only concern of requiring this keyword. I'm sure a lot of authors will forget to add this keyword and this flag should be added to all existing plugins (so authors should add or at least approve PR with this change and republish their package).

**Comment by BrainMaestro** [comment]
Before the change is made, we could have a regularly list of all plugins that have added the keyword and republished. Then we can only make the change when it has reached an acceptable level of completion (maybe 80%). Other people could also contribute by making the PRs to the different plugins.

Also, we could make it a setting. So by default in the next release all plugins are still shown with the option to show only platform specific plugins. Then later on after an adjustment period, it can now be the default behavior.

**Pull request merged**
