### PR TITLE
Switch to electrons getFileIcon on windows

### PR DESCRIPTION
**Pull request by SkaceKamen**
Removed win-icon-extractor and switched to electrons getFileIcon, which works the same way without additional dependencies.

Also fixed linux icons support.

### CODE REVIEW

**Comment by KELiON** [comment]
@maximbaz can you check how this method works on linux? If it works and handles different themes (#97) we can use it instead of reimplementing

**Comment by SkaceKamen** [comment]
I didn't switch to getFileIcon on linux, so it will work the same as before

**Comment by maximbaz** [comment]
I will try this method on linux later today on my own, to generally see what it does, because if it works nicely, we should definitely get rid of our custom code and just use it.

**Comment by maximbaz** [comment]
Unfortunately it doesn't work on Linux 😞 

When pointed to *.desktop file, for any of them it gives the same generic icon. When pointed to the executable file itself, it doesn't return any icon at all.

**Comment by SkaceKamen** [comment]
I'll try it on linux tomorrow, maybe I missed something or maybe it will be needed to switch to getFileIcon on linux too.

**Comment by maximbaz** [comment]
No no no, @SkaceKamen you did fix the original issue (thanks by the way!)
I was testing how electron's getFileIcon behaves on linux.

**Comment by SkaceKamen** [comment]
Oh, okay

**Comment by maximbaz** [comment]
But for regular files it returns some icon, so @KELiON `remote.app.getFileIcon` is not helpful for app icons, but can be used for the file search plugin.

**Comment by KELiON** [comment]
Ok, in this case we can merge this one and leave issue about app icon for Linux

**Comment by maximbaz** [comment]
To clarify: this PR fixes #256, but unfortunately we cannot use Electron's `getFileIcon` to retrieve app icons for Linux, that means we cannot get rid of our custom implementation in [basic-apps/linux.js](https://github.com/KELiON/cerebro/blob/master/app/main/plugins/core/basic-apps/linux.js) as all of us wished.

**Pull request merged**
