### PR TITLE
Feature/windows and linux support

### PR DESCRIPTION
**Pull request by KELiON**
* [x] Use png as plugin icon instead of `/Application/*.app` (calculator, plugins, settings, cerebro-shell);
* [x] Files and plugins: use OS separator instead of hardcoded `/`;
* [x] Launch on linux;
* [x] Test all plugins on linux
  * [x] Plugins install
  * [x] Plugins uninstall
  * [x] Autocomplete
  * [x] Files
  * [x] Calculator
  * [x] Converter
  * [x] Settings
  * [x] Google
  * [x] Maps
  * [x] Translate
  * [x] Open URL
* [x] Launch on windows;
* [x] Test all plugins on windows
  * [x] Plugins install
  * [x] Plugins uninstall
  * [x] Autocomplete
  * [x] Files
  * [x] Calculator
  * [x] Converter
  * [x] Settings
  * [x] Google
  * [x] Maps
  * [x] Translate
  * [x] Open URL

### CODE REVIEW

**Comment by staff0rd** [comment]
What kind of testing are we talking about here?  I tried (and for some reason didn't expect it to work) the calculator on windows and it seemed to work fine with basic arithmetic.

**Comment by KELiON** [comment]
@staff0rd if you have mac and windows, I'd just compare results (preview, behaviour in preview, i.e. in maps, icon/title/subtitle). And I'm almost sure that calculator, converter, maps, google and translate should already work on all systems because it is just plain js or web APIs without OS-specific features.

**Comment by KELiON** [comment]
Merged!

**Comment by staff0rd** [comment]
hmm - would have been better to merge the PR - difficult to see files/changes now

**Pull request closed without merging**
