### PR TITLE
Add windows system plugin

### PR DESCRIPTION
**Pull request by BrainMaestro**

### CODE REVIEW

**Comment by KELiON** [comment]
@BrainMaestro awesome, thanks for the contribution! 

Just a question: what is your use case for delay, like `lock in 5 seconds`?

**Comment by BrainMaestro** [comment]
Well the delay is mostly for shutdown and restart. An example could be waiting for a download to complete before shutting down. So you could set `shutdown in 30 seconds` or something.

**Comment by KELiON** [comment]
Oh, really. Or shut down after the movie ends. But you have to convert hours/minutes to seconds in this case)

**Comment by BrainMaestro** [comment]
Yea true. I could add a suffix (m, h, s) to qualify the time.

**Pull request merged**
