### PR TITLE
Feature/improve plugins

### PR DESCRIPTION
**Pull request by KELiON**
* Real-time plugins changes. In dev. mode page reloading is not needed anymore;
* Plugins autoupdate;
* Plugins cache invalidation;
* Better plugins names and descriptions;

### CODE REVIEW

**Comment by KELiON** [comment]
@maximbaz @AlexAlabyev hey guys, can you help me test this PR? I've created these builds (just from the latest master):

https://www.dropbox.com/s/hylenaysj374lqg/Cerebro%20Setup%200.2.6.exe?dl=0
https://www.dropbox.com/s/hy4p58nsom9p3i1/cerebro_0.2.6_amd64.deb?dl=0
https://www.dropbox.com/s/h8h98wb78bfov3a/cerebro-0.2.6-x86_64.AppImage?dl=0

Currently, I don't have an ability to test it on Windows and Linux, so would appreciate if you can help this it!

**Comment by maximbaz** [comment]
Sure! 

- When the app starts, it loads my existing extensions.
- When I install an extension, it is reported as installed (no restart). The console contains:

```
[npm] Install package cerebro-hash
main.bundle.js:25826 Version: 1.0.2
main.bundle.js:25778 Extract https://registry.npmjs.org/cerebro-hash/-/cerebro-hash-1.0.2.tgz to /home/maximbaz/.config/Cerebro/plugins/node_modules/cerebro-hash
main.bundle.js:25831 Add package to dependencies
```

- There are no errors, however if I look in the directory `/home/maximbaz/.config/Cerebro/plugins/node_modules/`, there is no `cerebro-hash` folder. 
- The extension therefore doesn't work, app restart also doesn't help.
- When I try to uninstall this extension, the button changes from "Uninstall" to "Uninstalling..." and then to "Uninstall" (not "Install"), so even from UI it is possible to tell that there is some problem.
- The console tells:

```
[npm] Uninstall package cerebro-hash
main.bundle.js:25856 Remove package directory  /home/maximbaz/.config/Cerebro/plugins/node_modules/cerebro-hash
main.bundle.js:25873 Error in package uninstallation
main.bundle.js:25874 Error: ENOENT: no such file or directory, lstat '/home/maximbaz/.config/Cerebro/plugins/node_modules/cerebro-hash'(…)
```

**Comment by maximbaz** [comment]
I had a quick look, I can see a couple of separate issues to handle:

1. [This line](https://github.com/KELiON/cerebro/blob/master/app/lib/plugins/npm.js#L40) sets `tempPath` to the temp folder (`/tmp` in my case), which has a lot of garbage from other apps. When the plugins are unpacked, they are unpacked directly in this folder, not in the subfolder. So the plugin files are getting all mixed up with other garbage. The solution is probably to use `const tempPath = os.tmpdir() + '/plugin-name'`.

2. Continuing from the previous item, [this line](https://github.com/KELiON/cerebro/blob/master/app/lib/plugins/npm.js#L51) is trying to move _the entire `/tmp` folder_ to `~/.config/Cerebro/plugins/node_modules/`. Luckily it doesn't succeed, because of .....

3. The `fs.rename` command that is used now does not work across partitions. In my case, `/tmp` and `~/` folders are located on different partitions. I found this accidentally [here](http://stackoverflow.com/a/8579946), see the second comment to this answer.

**Comment by AlexAlabyev** [comment]
@KELiON it all works fine on Windows. Also the `alt + f4` issue is fixed in this PR, I guess [https://github.com/KELiON/cerebro/issues/46](https://github.com/KELiON/cerebro/issues/46) can be closed now, as well.

**Comment by AlexAlabyev** [comment]
@KELiON sorry, I deleted the previous message, it's not working. I just noticed a few problems on Windows, as well, if you try to install a plugin now, it breaks everything:
- plugins don't work after installation. Even after the app restart. For example, If I install the clipboard plugin or the stackoverflow plugin and then try to type in `clipboard` or try to find anything via stackoverflow, now it's only showing google search results and not even triggering the plugins.
- Also you can't uninstall a plugin now, as @maximbaz described above, it stays in a state of `uninstall`


The `alt + f4` issue is fixed in this PR, though, I guess [https://github.com/KELiON/cerebro/issues/46](https://github.com/KELiON/cerebro/issues/46) can be closed now.

**Comment by KELiON** [comment]
@maximbaz wow, nice catch. Looks like on Windows it is the same problem @AlexAlabyev. Interesting, that on Mac `tmpPath` gives you temporary empty directory, so I even didn't think about this case. Going to fix everything! Thanks!

**Comment by KELiON** [comment]
@maximbaz @AlexAlabyev let's move discussion here #203

**Pull request merged**
