### PR TITLE
Update electron and electron-builder

### PR DESCRIPTION
**Pull request by Stanzilla**
Some package.json options are no longer valid with current electron-builder so I removed them. Might have to look into if they just got replaced or are just no longer needed.
```json
Error: Config is invalid:
{
  "homepage": "Unknown option",
  "category": "Unknown option",
  "linux": [
    {
      "arch": "Unknown option"
    },
    "Invalid option object"
  ]
}
```

### CODE REVIEW

**Comment by Stanzilla** [comment]
Weird, the tests don't fail local but on CI.

**Comment by Stanzilla** [comment]
So now that works but completely destroyed the scope of this PR, do you want me to split it?

**Comment by KELiON** [comment]
@Stanzilla can you just describe shortly what happened with linter and why you changed rules there?

**Comment by Stanzilla** [comment]
@KELiON Sure, it's just that the new AirBnB config and the react config got updated with more rules. I didn't want to sabotage your coding style so I disabled them so you can take a look yourself and change your code as you see fit.

**Pull request closed without merging**
