### PR TITLE
Added development context menu

### PR DESCRIPTION
**Pull request by staff0rd**
For whatever reason <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> or <kbd>F12</kbd> etc does not open dev tools on windows.  Added a (development only) context menu to enable this.

### CODE REVIEW

**Comment by KELiON** [comment]
I'd change it a bit. Can you add this to submenu "Development"? I'd display next items: 

* DevTools (main);
* DevTools (background);
* Reload;

Currently, there are two electron windows: main and background (always hidden) and there is no way to show dev tools for background window. But it can be useful for plugins with async initialization, like contacts.

What do you think? Let me know if you need any help

**Comment by staff0rd** [comment]
Done.  The reference to backgroundWindow dev tools is a bit hacky - maybe `AppTray` initialization needs to be extracted from `main.createWindow`?

**Comment by KELiON** [comment]
@staff0rd cool, thanks! 

> maybe AppTray initialization needs to be extracted from main.createWindow

yes, makes sense. I think we can just pass `mainWindow` and `backgroundWindow` as props to AppTray and do everything inside. In this case we can also change `reload` action to reload both main and background windows

**Comment by staff0rd** [comment]
@KELiON had a brief look at it, but I think the refactor is a little larger job than I'd like to take on - I see many possibilities, but don't really have the time atm.

**Comment by KELiON** [comment]
@staff0rd not a problem! Thanks for idea and initial implementation, I pushed few changes in your branch, will merge it later today

**Pull request merged**
