### PR TITLE
Feature/remove apps preview

### PR DESCRIPTION
**Pull request by KELiON**
Remove previews from applications plugins: it doesn't make sense to show app size, big icon and other information for the application file, most of the users just launch the app:

screen shot 2017-03-13 at 23 31 18

### CODE REVIEW

**Comment by Kageetai** [comment]
Hmm, I personally kinda liked the big icons etc. Is there any downside to displaying it?

**Comment by KELiON** [comment]
@Kageetai I don't see any advantages of showing these icons – it is just duplication of information (these icons are already in results list).

**Comment by maximbaz** [comment]
I'm with @Kageetai on this one, I kinda like the big beautiful icons too, it's a bit boring without them 😄 

In my mind, this piece of info is useless, but the icon itself is fine 😃

image

**Comment by KELiON** [comment]
@maximbaz @Kageetai Ok, you won :D

**Pull request closed without merging**
