### PR TITLE
cleanups and dependency updates

### PR DESCRIPTION
**Pull request by Stanzilla**
* fix missing deps
* add a `yarn clean` command using rimraf
* switch CI node from 7 to 8 (LTS)
* switch yarn cache and installation to the preferred methods
* react-addons-css-transition-group is now react-transtion-group
* react-virtualized was updated to the latest version and the code now uses their List component (this might be wrong and need some work)
* node engine is now >=8.0

### CODE REVIEW

**Comment by maximbaz** [comment]
I wonder if it is possible to make Travis build Cerebro not only against LTS node (which is 8 now), but also against the current version (which is 9 now)?

This would have prevented #426, which blocks upgrading cerebro on the entire Arch Linux distribution.

**Comment by Stanzilla** [comment]
Yes, Travis supports a matrix mode

**Comment by KELiON** [comment]
Hey, @Stanzilla! Thanks for this great job! For me everything looks good but I found one bug, I think it is related to new version of react-virtualized. Issue is: if I hold arrow down in current version of Cerebro I properly see list of results, but after update it is hidden after few results. 


Before: http://recordit.co/Zd4UL0mF7l
After: http://recordit.co/Zd4UL0mF7l

Would be great if you can fix it before I merge this PR

**Comment by Stanzilla** [comment]
Yeah it is and I think it might be either using the wrong component or need a newer react version, I sadly don't know too much about that. Would be awesome if you could help?

**Comment by KELiON** [comment]
@Stanzilla ок, I'll try to find the reason a bit later

**Comment by Stanzilla** [comment]
added one more commit based on https://github.com/bvaughn/react-virtualized/blob/master/docs/creatingAnInfiniteLoadingList.md it's a WIP though, maybe you can finish it with that.

**Comment by Stanzilla** [comment]
@KELiON haven't had any time to take a look yet? :)

**Comment by Stanzilla** [comment]
@KELiON friendly ping :)

**Pull request closed without merging**
