### PR TITLE
plugin cerebro-gkg (https://github.com/Kageetai/cerebro-gkg)

### PR DESCRIPTION
**Pull request by Kageetai**
H there, I found your nice project here and liked the functionality and style (compared to other electron-based launchers out there) and decided to try myself on a little first plugin, also to learn more about ES6 and React.
Just something simple to look up the Google Knowledge Graph and display the results. Maybe you have some tipps to improve the plugin etc. :)

### CODE REVIEW

**Comment by KELiON** [comment]
@Kageetai hi there and thanks for you contribution, you are the first one who submits a plugin! 

It looks great, but I found one thing. There is a [limitation](https://developers.google.com/knowledge-graph/reference/rest/v1/usage-limits) of API usage for knowledge graph, 100,000 requests per day for your API key. Looks like it is a lot, but in your approach you are doing API request for each change in search input. It means if I enter `how are you in spanish` this plugin will do 22 requests to API. So, 1,000 users will reach API limit really fast.

Solution is requesting API only when it is needed. There are two ways:

1) You can scope knowledge graph seach with some keyword, like it is done in [gifs](https://github.com/KELiON/cerebro-gif/blob/master/src/index.js#L41) or [maps](https://github.com/KELiON/cerebro/blob/master/app/main/plugins/core/maps/index.js#L33) plugins.

2) When user enters `blabla` you can display result `Search blabla in Google Knowledge Graph`, and when user set focus to this result you can request API from `Preview` and display results like it is done in [google](https://github.com/KELiON/cerebro/tree/master/app/main/plugins/core/google) plugin.

**Comment by Kageetai** [comment]
Thanks for the comments. Totally my first try on a plugin for something like this. :)

Your concerns are of course right. I think the second solution sounds good to me. Will implement that.

I also noticed, when I install the plugin in cerebro itself, the result shows up twice in the list. But when I just run it in development, it only shows up once, like supposed to. Do you have any idea how this is happening?

**Comment by KELiON** [comment]
@Kageetai can you attach a screenshot? Also, would be cool if you can check what do you have in console:

1) Type settings and turn on developer mode, turn on "show in menu bar";
2) Toggle Cerebro window and from tray menu select development → dev tools (main), switch to `console` tab;
3) Reload everything (tray  →development → reload);
4) Check what do you have in `Load external plugins` block.

**Comment by Kageetai** [comment]
@KELiON weird, now this behaviour is gone and works fine. I will report of it happens again...

**Comment by Kageetai** [comment]
HI @KELiON I updated the plugin. Can you take another look. I've got two problems:
1. How can use the retrieved from the promise in `action.open`?
2. I was trying to set up a similar way to process the CSS for the plugin as you did for the core plugins, but just can't get the webpack/postcss config to work. [Can you help out?](https://github.com/Kageetai/cerebro-gkg/commit/d3c34cd18a01b85aa586b78407d87ebc2b68de70)

**Comment by KELiON** [comment]
@Kageetai it looks really good! I'll check it more detailed tomorrow, but for now, I'd add only two things:

1) I'd loading animation during fetching information from API, i.e. you can check [google plugin](loader)
2) Error handling: you can show some simple message if any error occurs, like `Sorry, but nothing found`). I.e. I tried to search for `Berlin` (with first capital letter), but `berlin` works well.

**Comment by Kageetai** [comment]
@KELiON Thanks.
1. I noticed that component already, but didn't want to just copy the Preview and the Preloader from the base components, because I thought maybe there is a way to reuse those? Because copying those to every new plugin would be quite redundant, I think.
2. For error handling or at least no useful results, I wanted to just not display the result in the list. But I also figured that still needs some fine-tuning.
3. In the `onSelect` event handler (currently empty/commented out) I wanted to open the url returned from the result/promise, but I am unsure how to get that data back up there. Is that possible and if so, do you have a hint?

**Comment by KELiON** [comment]
@Kageetai I know about problem with duplication of components and I want to release common components as a standalone npm module, so they can be reused. 

Regarding `onSelect`: it is a bit hacky, but you can call `update(id, {onSelect: () => {...}}` from your Preview when data is loaded. Do you have any ideas on how I can improve plugins API?

**Pull request merged**
