### PR TITLE
Update a few devDeps

### PR DESCRIPTION
**Pull request by Stanzilla**
electron-builder is still pretty old but I did not want to deal with conflicts that happened after upgrading to anything above the 13.x series.

To document them, this is what happened when trying the last version of 14.x:

```
Error: Config is invalid:
{
  "homepage": "Unknown option",
  "category": "Unknown option",
  "linux": [
    {
      "arch": "Unknown option"
    },
    "Invalid option object"
  ],
  "win": [
    {
      "target": [
        "Should be array",
        "Invalid option object"
      ]
    },
    "Invalid option object"
  ]
}

Raw validation errors: [
  {
    "keyword": "additionalProperties",
    "dataPath": "",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "homepage"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "additionalProperties",
    "dataPath": "",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "category"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "additionalProperties",
    "dataPath": ".linux",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "arch"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "type",
    "dataPath": ".linux",
    "schemaPath": "#/properties/linux/anyOf/1/type",
    "params": {
      "type": "null"
    },
    "message": "should be null"
  },
  {
    "keyword": "anyOf",
    "dataPath": ".linux",
    "schemaPath": "#/properties/linux/anyOf",
    "params": {},
    "message": "should match some schema in anyOf"
  },
  {
    "keyword": "type",
    "dataPath": ".win.target",
    "schemaPath": "#/properties/target/anyOf/0/type",
    "params": {
      "type": "array"
    },
    "message": "should be array"
  },
  {
    "keyword": "type",
    "dataPath": ".win.target",
    "schemaPath": "#/properties/target/anyOf/1/type",
    "params": {
      "type": "null"
    },
    "message": "should be null"
  },
  {
    "keyword": "anyOf",
    "dataPath": ".win.target",
    "schemaPath": "#/properties/target/anyOf",
    "params": {},
    "message": "should match some schema in anyOf"
  },
  {
    "keyword": "type",
    "dataPath": ".win",
    "schemaPath": "#/properties/win/anyOf/1/type",
    "params": {
      "type": "null"
    },
    "message": "should be null"
  },
  {
    "keyword": "anyOf",
    "dataPath": ".win",
    "schemaPath": "#/properties/win/anyOf",
    "params": {},
    "message": "should match some schema in anyOf"
  }
]
    at C:\Users\Benjamin\Documents\VCS\Git\cerebro\node_modules\electron-builder\src\util\readPackageJson.ts:151:11
From previous event:
    at validateConfig (C:\Users\Benjamin\Documents\VCS\Git\cerebro\node_modules\electron-builder\out\util\readPackageJson.js:1
55:22)
    at C:\Users\Benjamin\Documents\VCS\Git\cerebro\node_modules\electron-builder\src\packager.ts:128:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Packager.build (C:\Users\Benjamin\Documents\VCS\Git\cerebro\node_modules\electron-builder\out\packager.js:257:11)
    at C:\Users\Benjamin\Documents\VCS\Git\cerebro\node_modules\electron-builder\src\builder.ts:217:33
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\Benjamin\Documents\VCS\Git\cerebro\node_modules\electron-builder\out\builder.js:70:21)
    at Object.<anonymous> (C:\Users\Benjamin\Documents\VCS\Git\cerebro\node_modules\electron-builder\out\cli\build-cli.js:71:4
1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:148:9)
    at bootstrap_node.js:542:3
error Command failed with exit code 4294967295.
```

### CODE REVIEW

**Comment by KELiON** [comment]
So, it is not clear for me from you comment. With this update everything is fine and everything works, but if we want to use latest `electron-builder` – we should resolve some conflicts. Correct?

**Comment by Stanzilla** [comment]
@KELiON correct. I'm just trying to learn a bit of JS/yarn/npm atm so those PRs are me experimenting but I hope it is at least of some use for you. :)

**Comment by KELiON** [comment]
@Stanzilla it is useful, thanks! Only one thing to change: when we update version of electron we should also update it in `build` script in app/package.json

**Comment by Stanzilla** [comment]
Indeed! Done.

**Comment by KELiON** [comment]
Thanks, @Stanzilla!

**Pull request merged**
