### PR TITLE
Make config.json nicely formatted

### PR DESCRIPTION
**Pull request by maximbaz**
As a Linux user I like human-readable configs, so I want a nicely formatted json.

Since I keep my cerebro config along with other dotfiles in a git repo, I don't want to see keys being reordered all the time, so I used a deterministic JSON formatter instead of the standard JSON.stringify.

### CODE REVIEW

**Comment by KELiON** [comment]
@maximbaz how do you use this config? Everything, that could be changed by user you can change in app settings. And `config.json` is just a system file, that is not supposed to be read/edited by people.

**Comment by maximbaz** [comment]
My primary case: I keep this config in the [git repo](https://github.com/maximbaz/dotfiles/tree/master/.config/Cerebro) along with all my configuration files, what allows me to quickly set up new system when I need it. And currently it's difficult to review the `git diff` when something changes in the config.

**Comment by KELiON** [comment]
@maximbaz In this case I'd suggest you just to beaufity the file in some editor before adding it to git repo. In this case you can always have the same format/keys sorting, so it will help you to see better diff. 

Is this package have native bindings (it is only one case to add a module to `app/package.json` instead of `./package.json` in root folder)?

Anyway, in my opinion it is special case and adding new dependency is too much for that. What do you think?

**Comment by maximbaz** [comment]
That's the kind of hassle I was trying to avoid 🙂 

If the concern is about adding the external library, how about we still prettify it, but only by using the default JSON class? So instead of `JSON.stringify(config)` it will become `JSON.stringify(config, null, 2)`. This doesn't guarantee order of keys so sometimes they will be shuffled around, but I guess it will still be better for me.

**Comment by maximbaz** [comment]
Honestly I would use `JSON.stringify(obj, null, 2)` in all other places as well, it doesn't harm but if you ever need to open it, for debugging purposes or similar, the files are at least readable.

**Comment by KELiON** [comment]
@maximbaz it is perfect! I even didn't know about this arguments)

**Pull request merged**
