### PR TITLE
Single Instance Application

### PR DESCRIPTION
**Pull request by Schrims**
Issue: https://github.com/KELiON/cerebro/issues/229
Solution: https://github.com/electron/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback

### CODE REVIEW

**Comment by KELiON** [comment]
@Schrims looks good! There is only one linter error, can you fix it?

This PR should also fix #138.

**Comment by maximbaz** [comment]
Nah, in #138 it's not a question about running a second instance of cerebro, but rather a question of whether cerebro itself should create a second instance of any app that it starts (chrome, calculator, etc.), when another instance of that app already exists.

**Comment by KELiON** [comment]
@maximbaz oops, exactly

**Comment by Schrims** [comment]
@KELiON I'm not sure if I removed the trailing-space correctly - but we will see 👍

**Pull request merged**
