### PR TITLE
Do not decrease window height until hidden

### LINKED ISSUE #401: Mouse focus issue
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 17.10 x64
- **Cerebro.app version**: 0.3.1

## Issue
I have my system configured so that it will switch focus to the app under mouse cursor. When Cerebro changes its window size on typing it often (when mouse was over Cerebro's window) causes focus to be stolen by an app below it. Here is a short demo: https://nextcloud.mokrynskyi.com/s/ebV9BIwgZaBEXQE

I think the simplest solution would be to never reduce the size of opened window. Growing from single line to search results is fine, but never backwards. At least optionally.

### PR DESCRIPTION
**Pull request by nazar-pc**
Fixes #401

### CODE REVIEW

**Comment by raphaklaus** [comment]
Is there any prevision to merge this PR?

**Comment by nazar-pc** [comment]
What do you mean?

**Comment by raphaklaus** [comment]
This PR is still opened. What needs to be done to merge it on master and release this fix?

**Comment by nazar-pc** [comment]
We need a review from maintainers first. Looks like they're busy with other stuff or simply do not care.

**Comment by nazar-pc** [comment]
@KELiON, could you take a look at this, please?

**Comment by KELiON** [comment]
Sorry for the long delay, @nazar-pc! I just checked your PR and I think it is not useful for _all_ users, it fixes just your own case. As a user I don't want to steal 50% of my screen with empty window when I do `<kbd>cmd+a, backspace</kbd>` to clear search field. I.e. I often do it just to see something in the background before search/action. 

Do you have other ideas to fix this?

**Comment by nazar-pc** [comment]
I'd be happy with option in UI disabled by default or at least config file option for this behavior. Is this something you can add?

**Comment by nazar-pc** [comment]
Also I don't really understand why you might need to clean search window, but keep Cerebro open. You can as well just close it and reopen when needed.

**Comment by brunofunnie** [comment]
**OS Version:** Ubuntu 18.04
**Cerebro Version:** 0.3.2 (AppImage)

The issue happens randomly when pressing ctrl+space and typing something and then pressing ctrl+space twice to close and open again. It happens using ESC to hide too and then open with ctrl+space. It's intermittent

cerebro_bug

**Pull request closed without merging**
